# config.yaml
open_api:
  spec_dir: app/controllers/spec
  api_doc: openapi.yaml

service:
  port: 5000

mongo_database:
  database_url: mongodb://admin:password@localhost:27017
  database_name: voting_db
