openapi: 3.0.0
info:
  title: Simple API
  version: "1.0"
paths:
  /api/v1/sample:
    get:
      operationId: api.sample_controller.get_greeting
      summary: Returns a greeting message
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
